#!/bin/sh

REF="data/ref/$1/"
OUT="data/output/$1/"

CT=1
while [ -f "$OUT$CT" ]; do
  if [ ! -f "$REF$CT" ]; then
    echo "There are more output files than reference files. Exiting."
    exit 1
  fi

  REFDATA=$(cat $REF$CT | tr -d '\r')
  echo "$REFDATA" > $REF$CT
  OUTDATA=$(cat $OUT$CT | tr -d '\r')
  echo "$OUTDATA" > $OUT$CT

  echo "============================================================"
  #printf "Difference between files \n\t%s\nand \t%s\n\n" "$REF$CT" "$OUT$CT"
  eval diff -u -s -a "$REF$CT" "$OUT$CT"
  CT=$((CT+1))
done
