#!/bin/sh

GENTO="data/ref/$1"
INPUT=$(eval cat "data/input/$1")

eval mkdir -p data
eval mkdir -p data/ref
eval rm -rf "$GENTO"
eval mkdir "$GENTO"
eval rm stock-*
eval cp stonks/* ./

CT=1
ACTLINE=$(echo "$INPUT" | head -1)
INPUT=$(echo "$INPUT" | tr '\n' ';' | cut -d ';' -f2- | tr ';' '\n')
ACTOUT="$GENTO/$CT"
while [ -n "$ACTLINE" ]; do
  printf "Writing output of \n\t%s\nto \t%s\n\n" "$ACTLINE" "$ACTOUT"
  eval "$ACTLINE" > "$ACTOUT"

  CT=$(($CT+1))
  ACTLINE=$(echo "$INPUT" | head -1)
  INPUT=$(echo "$INPUT" | tr '\n' ';' | cut -d ';' -f2- | tr ';' '\n')
  ACTOUT="$GENTO/$CT"
done
eval rm stock*

echo "Done generating reference output"
