#!/bin/sh

INPUT=$(eval cat "data/input/$1")
REF="data/ref/$1"
OUT="data/output/$1"

eval mkdir -p data
eval mkdir -p data/output
eval rm -rf "$OUT"
eval mkdir "$OUT"
eval rm stock-*
eval cp stonks/* ./

CT=1
ACTLINE=$(echo "$INPUT" | head -1)
INPUT=$(echo "$INPUT" | tr '\n' ';' | cut -d ';' -f2- | tr ';' '\n')
ACTOUT="$OUT/$CT"
while [ -n "$ACTLINE" ]; do
  echo -e "Writing output of \n\t$ACTLINE\nto \t$ACTOUT\n"
  eval "$ACTLINE" | tr -d '\r' > "$ACTOUT"

  CT=$(($CT+1))
  ACTLINE=$(echo "$INPUT" | head -1)
  INPUT=$(echo "$INPUT" | tr '\n' ';' | cut -d ';' -f2- | tr ';' '\n')
  ACTOUT="$OUT/$CT"
done
eval rm stock*

eval "./compare $1"
